name: "Sort and update plain text files"

# Credits to Chilihero (https://github.com/nikolaischunk/discord-phishing-links/blob/main/.github/workflows/update.yml)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events when some specific files change
  push:
    branches:
      - main
    paths:
      - "responses.json"
      - "rickrolls.json"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-repository:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # use personal token instead of GITHUB_TOKEN
          fetch-depth: 0

      # Use JQ for json sorting and json parser
      - uses: sergeysova/jq-action@v2

      - name: Sort responses.json
        continue-on-error: false
        run: "jq '.list |= (sort | unique)' responses.json > tmp-responses.json && mv tmp-responses.json responses.json"

      - name: Sort rickrolls.json
        continue-on-error: false
        run: "jq '.rickrolls |= (sort | unique)' rickrolls.json > tmp-rickrolls.json && mv tmp-rickrolls.json rickrolls.json"

      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add .
          git commit -m "✨ Sorted Domains automatically" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
